periodTime:
    measureTemp: 1
    sendRecMess: 2

iotHub:
    connectionString: "HostName=thesis-hub.azure-devices.net;DeviceId=test-device;SharedAccessKey=E/uKH6XK6G2NLCYWQxu26+mrNBKmecm0I4WU2A1FfrY="
    msgFormat: '{{"personID": "{personID}","temperature":"{temperature}","embedding": "{embedding}"}}'

camera:
    rgb:
        source: "nvarguscamerasrc ! video/x-raw(memory:NVMM), 
        width=(int)1920, height=(int)1080,format=(string)NV12, 
        framerate=(fraction)29/1 ! nvvidconv flip-method=2 ! video/x-raw, 
        format=(string)BGRx ! videoconvert ! video/x-raw, 
        format=(string)BGR ! appsink"
        scaleWidth: 768
        scaleHeight: 432
    thermal: 
        source: "/dev/spidev0.0"
        scaleWidth: 640
        scaleHeight: 480
    
faceDetection:
    modelSsd: "./submodules/face_detection/models/res10_300x300_ssd_iter_140000.caffemodel"
    protoSsd: "./submodules/face_detection/models/deploy.prototxt.txt"
    modelSlim320: "./submodules/face_detection/models/slim-320.caffemodel"
    protoSlim320: "./submodules/face_detection/models/slim-320.prototxt"
    onnxSlim320: "./submodules/face_detection/models/version-slim-320_simplified.onnx" 

transMatrix: [[ 3.27462156e+00, 7.23169874e-01, -6.78237088e+02],
    [-3.69846362e-01,  5.45383143e+00, -1.36312869e+03],
     [-2.37831103e-04,  4.22887587e-03,  1.00000000e+00]]

maxDisFramesObjectTracking: 50

registration:
    numFontPics: 5
    numLeftPics: 5
    numRightPics: 5
