periodTime:
    measureTemp: 1
    sendRecMess: 2

iotHub:
    connectionStringDevice: "HostName=thesis-hub.azure-devices.net;DeviceId=test-device;SharedAccessKey=E/uKH6XK6G2NLCYWQxu26+mrNBKmecm0I4WU2A1FfrY="
    connectionStringBlob: "DefaultEndpointsProtocol=https;AccountName=thesisbstorage;AccountKey=WdOJMq9wULxCEKKHHiI9lafWPjIpJpXuinasmDLO5F9zZObHDzrLxTszglLM0zCa+GILFbjZCTO0BjFEuUR/WQ==;EndpointSuffix=core.windows.net"
    msgFormat: '{{"personID": "{personID}","temperature":"{temperature}","embedding": "{embedding}"}}'

camera:
    rgb:
        source: "nvarguscamerasrc ! video/x-raw(memory:NVMM), 
        width=(int)1920, height=(int)1080,format=(string)NV12, 
        framerate=(fraction)29/1 ! nvvidconv flip-method=2 ! video/x-raw, 
        format=(string)BGRx ! videoconvert ! video/x-raw, 
        format=(string)BGR ! appsink"
        scaleWidth: 768
        scaleHeight: 432
    thermal: 
        source: "/dev/spidev0.0"
        scaleWidth: 640
        scaleHeight: 480
    
faceDetection:
    modelSsd: "./submodules/face_detection/models/res10_300x300_ssd_iter_140000.caffemodel"
    protoSsd: "./submodules/face_detection/models/deploy.prototxt.txt"
    modelSlim320: "./submodules/face_detection/models/slim-320.caffemodel"
    protoSlim320: "./submodules/face_detection/models/slim-320.prototxt"
    onnxSlim320: "./submodules/face_detection/models/version-slim-320_simplified.onnx" 
    faceSize: 600

transMatrix: [[ 1.38561524e+00, -5.27680134e-04, -1.23831453e+02],
 [ 4.82426727e-02 , 1.47376946e+00 ,-1.49092213e+02],
 [-1.60874186e-04 , 1.36021487e-04 , 1.00000000e+00]]


maxDisFramesObjectTracking: 50

registration:
    numFontPics: 5
    numLeftPics: 5
    numRightPics: 5

display:
    enableThermalFrame: True
