buildingId: 1
deviceId: 'test-device'

periodTime:
    measureTemp: 1
    sendRecMess: 2

iotHub:
    connectionStringDevice: "HostName=thesis-hub.azure-devices.net;DeviceId=test-device;SharedAccessKey=E/uKH6XK6G2NLCYWQxu26+mrNBKmecm0I4WU2A1FfrY="
    connectionStringBlob: "DefaultEndpointsProtocol=https;AccountName=thesisbstorage;AccountKey=WdOJMq9wULxCEKKHHiI9lafWPjIpJpXuinasmDLO5F9zZObHDzrLxTszglLM0zCa+GILFbjZCTO0BjFEuUR/WQ==;EndpointSuffix=core.windows.net"
    msgFormat: 
        recMsg: '{{"buildingId":"{buildingId}","deviceId":"{deviceId}","trackingId": "{trackingId}","face": "{face}"}}'
        recordMsg: '{{"buildingId":"{buildingId}","personId": "{personID}", "personName": "{personName}", "temperature":"{temperature}", "face":"{face}"}}'
        registerMsg: '{{"buildingId":"{buildingId}","personName": "{personName}","containerName":"{containerName}"}}'
    enableSending: False

camera:
    rgb:
        source: "nvarguscamerasrc ! video/x-raw(memory:NVMM), 
        width=(int)1920, height=(int)1080,format=(string)NV12, 
        framerate=(fraction)29/1 ! nvvidconv flip-method=2 ! video/x-raw, 
        format=(string)BGRx ! videoconvert ! video/x-raw, 
        format=(string)BGR ! appsink"
        scaleWidth: 768
        scaleHeight: 432
    thermal: 
        source: "/dev/spidev0.0"
        scaleWidth: 640
        scaleHeight: 480
    
faceDetection:
    modelSsd: "./submodules/face_detection/models/res10_300x300_ssd_iter_140000.caffemodel"
    protoSsd: "./submodules/face_detection/models/deploy.prototxt.txt"
    modelSlim320: "./submodules/face_detection/models/slim-320.caffemodel"
    protoSlim320: "./submodules/face_detection/models/slim-320.prototxt"
    modelRfb320: "./submodules/face_detection/models/RFB-320.caffemodel"
    protoRfb320: "./submodules/face_detection/models/RFB-320.prototxt"
    onnxSlim320: "./submodules/face_detection/models/version-slim-320_simplified.onnx" 
    faceSize: 600

transMatrix: [[2.272738307672771629341923471656627953052520751953125000000000,0.391976965091863138734851190747576765716075897216796875000000,-485.582072400344941343064419925212860107421875000000000000000000],[0.031887711541247483471028800749991205520927906036376953125000,2.537309936688716849317870583035983145236968994140625000000000,-497.773711960723801439598901197314262390136718750000000000000000],[0.000430438068276405580783738891170742135727778077125549316406,0.001177245091736771115051296554554483009269461035728454589844,0.999999999999999888977697537484345957636833190917968750000000]]



maxDisFramesObjectTracking: 40

registration:
    numFontPics: 2
    numLeftPics: 2
    numRightPics: 2
    stackNumberPics: 6
    leftThreshold: -18
    rightThreshold: 15
    frontRange: 44
    frameBetweenCapture: 3

measureTemperature:
    offsetTemperature: 3
    numberMaxThermalPoints: 16
    offsetDistCoeffecient: -0.0000212
    offsetDistIntercept: 1.654018585

display:
    enableThermalFrame: False
