deviceIdAzure: 'test-device'
deviceLabel: 'TMC-2021-1-00000001'

offlineRecordDirectory: 'device_app/data/offline_records/'

periodTime:
    measureTemp: 0.8
    sendRecMess: 2

iotHub:
    connectionStringDevice: "HostName=tkt-hub.azure-devices.net;DeviceId=test-device;SharedAccessKey=FOqwhgsa2JtBmW7Pr521Sh3ICstAFZgjWUCL7eoaCkU="
    connectionStringBlob: "DefaultEndpointsProtocol=https;AccountName=tktrecordstorage;AccountKey=L5yEM18qRAUaAvYiFkwQC1T54rl+ceLvhu6EeDVXr1vOBfvMn6mzoAoagM/WBwUiQJy4gYxNM5aSiDQlzIxtsg==;EndpointSuffix=core.windows.net"
    msgFormat: 
        recMsg: '{{"buildingId":"{buildingId}","deviceId":"{deviceId}","trackingId": "{trackingId}","face": "{face}"}}'
        recordMsg: '{{"method":"storeRecord","data":{{"deviceLabel":"{deviceLabel}","personId": "{personID}", "temperature":"{temperature}", "face":"{face}", "masked":"{masked}", "recordTime":"{recordTime}" , "internetAvailable":"{internetAvailable}"}}}}'
        registerMsg: '{{"deviceId":"{deviceId}","buildingId":"{buildingId}","registerCode": "{registerCode}","containerName":"{containerName}"}}'
        activeDeviceMsg: '{{"method":"loginDevice","data":{{"deviceId":"{deviceId}", "deviceLabel":"{deviceLabel}","pinCode": "{pinCode}"}}}}'
    enableAllSending: False     # (True) will overwrite all other sending flags 
    enableSendingRecognite: False
    enableSendingRecord: False
    enableSendingRegister: False

camera:
    rgb:
        source: 'nvarguscamerasrc ! video/x-raw(memory:NVMM), 
        width=(int)1920, height=(int)1080,format=(string)NV12, 
        framerate=(fraction)29/1 ! nvvidconv flip-method=6 ! video/x-raw, 
        format=(string)BGRx ! videoconvert ! video/x-raw, 
        format=(string)BGR ! appsink max-buffers=1 drop=True'
        originalWidth: 1920
        originalHeight: 1080
        # scaleWidh and scaleHeight must follow the ratio 16/9, change this scale values to change the perfomance of face detection
        scaleWidth: 768
        scaleHeight: 432
    thermal: 
        source: "/dev/spidev0.0"
        originalWidth: 80
        originalHeight: 60
        scaleWidth: 640
        scaleHeight: 480
    
faceDetection:
    modelSsd: "./device_app/submodules/face_detection/models/res10_300x300_ssd_iter_140000.caffemodel"
    protoSsd: "./device_app/submodules/face_detection/models/deploy.prototxt.txt"
    modelSlim320: "./device_app/submodules/face_detection/models/slim-320.caffemodel"
    protoSlim320: "./device_app/submodules/face_detection/models/slim-320.prototxt"
    modelRfb320: "./device_app/submodules/face_detection/models/RFB-320.caffemodel"
    protoRfb320: "./device_app/submodules/face_detection/models/RFB-320.prototxt"
    onnxSlim320: "./device_app/submodules/face_detection/models/version-slim-320_simplified.onnx"
    landmarkDetectionModel: "./device_app/submodules/face_detection/models/landmarks.dat"
    faceSize: 400
    threshold: 0.6

transMatrix: [[0.719298243522644042968750000000000000000000000000000000000000,0.000000000000000000000000000000000000000000000000000000000000,108.140350341796875000000000000000000000000000000000000000000000],[-0.000000000000000052438578919762255086539637360942833765875548,0.736842095851898193359375000000000000000000000000000000000000,219.368423461914062500000000000000000000000000000000000000000000]]

transMatrixPnP:
    rotationVector: [[0.277155127679242496707701093328068964183330535888671875000000],[-0.052957700811528750362011663810335448943078517913818359375000],[-0.007994345064430837324853662551049637841060757637023925781250]]
    translationVector: [[-410.774927437732912949286401271820068359375000000000000000000000],[-166.678268796243912674981402233242988586425781250000000000000000],[791.260798151535368560871575027704238891601562500000000000000000]]
    thermalCameraMatrix: [[640,0,320],[0,640,240],[0,0,1]]
    distortionCoefficients: [[0],[0],[0],[0]]

thresholdFaceMaskDetection: 75

registration:
    numFontPics: 5
    numLeftPics: 5
    numRightPics: 5
    stackNumberPics: 6
    frameBetweenCapture: 3
    frontRange: 44
    leftThreshold: -18
    rightThreshold: 15


measureTemperature:
    numberMaxThermalPoints: 2
    # offsetDistCoeffecient: -0.0000212
    # offsetDistIntercept: 1.654018585
    offsetDistCoeffecient: -0.347698157
    offsetDistIntercept: 4.557706084
    percentageThermalPoints: 0.17
    temperatureMeasureMethod: 2
    # Method 1: apply in one-person mode -> Get N highest-temp pixels -> find 8 neighbor pixels and calculate the average temp, standard deviation 
    # Method 2: apply in multi-person mode -> Choose percentage of captured pixels that has the highest temp and find the average temp of them
    temperatureStandardDeviationThreshold: 0.5

personTracking:
    minFaceSizeOfNormalMode: 9000
    maxFaceSizeOfOnePersonMode: 450000
    minFaceSizeOfOnePersonMode: 350000
    noOfDisapearFrames: 30
    noOfDisapearFramesForCalib: 15
    recordFaceSize: 500
    bufSizeTempPersonTracking: 6
    bufSizeNameAndIdPersonTracking: 3

developmentFlags:
    printProcessTime: False
    printReceiveData: False
    printSendData: False
    printRecord: False
    printRecognize: False
    printRegister: True
    printIoTConn: True
    printGarbageFrams: False