buildingId: 1
deviceId: 'test-device'

periodTime:
    measureTemp: 0.9
    sendRecMess: 2

iotHub:
    connectionStringDevice: "HostName=thesis-hub.azure-devices.net;DeviceId=test-device;SharedAccessKey=E/uKH6XK6G2NLCYWQxu26+mrNBKmecm0I4WU2A1FfrY="
    connectionStringBlob: "DefaultEndpointsProtocol=https;AccountName=thesisbstorage;AccountKey=WdOJMq9wULxCEKKHHiI9lafWPjIpJpXuinasmDLO5F9zZObHDzrLxTszglLM0zCa+GILFbjZCTO0BjFEuUR/WQ==;EndpointSuffix=core.windows.net"
    msgFormat: 
        recMsg: '{{"buildingId":"{buildingId}","deviceId":"{deviceId}","trackingId": "{trackingId}","face": "{face}"}}'
        recordMsg: '{{"buildingId":"{buildingId}","personId": "{personID}", "personName": "{personName}", "temperature":"{temperature}", "face":"{face}"}}'
        registerMsg: '{{"buildingId":"{buildingId}","personName": "{personName}","containerName":"{containerName}"}}'
    enableSending: False

camera:
    rgb:
        source: 'nvarguscamerasrc exposuretimerange="10000000 10000000" ! video/x-raw(memory:NVMM), 
        width=(int)1920, height=(int)1080,format=(string)NV12, 
        framerate=(fraction)29/1 ! nvvidconv flip-method=2 ! video/x-raw, 
        format=(string)BGRx ! videoconvert ! video/x-raw, 
        format=(string)BGR ! appsink max-buffers=1 drop=True'
        scaleWidth: 768
        scaleHeight: 432
    thermal: 
        source: "/dev/spidev0.0"
        scaleWidth: 640
        scaleHeight: 480
    
faceDetection:
    modelSsd: "./device_app/submodules/face_detection/models/res10_300x300_ssd_iter_140000.caffemodel"
    protoSsd: "./device_app/submodules/face_detection/models/deploy.prototxt.txt"
    modelSlim320: "./device_app/submodules/face_detection/models/slim-320.caffemodel"
    protoSlim320: "./device_app/submodules/face_detection/models/slim-320.prototxt"
    modelRfb320: "./device_app/submodules/face_detection/models/RFB-320.caffemodel"
    protoRfb320: "./device_app/submodules/face_detection/models/RFB-320.prototxt"
    onnxSlim320: "./device_app/submodules/face_detection/models/version-slim-320_simplified.onnx"
    landmarkDetectionModel: "./device_app/submodules/face_detection/models/landmarks.dat"
    faceSize: 600

transMatrix: [[0.719298243522644042968750000000000000000000000000000000000000,0.000000000000000000000000000000000000000000000000000000000000,108.140350341796875000000000000000000000000000000000000000000000],[-0.000000000000000052438578919762255086539637360942833765875548,0.736842095851898193359375000000000000000000000000000000000000,219.368423461914062500000000000000000000000000000000000000000000]]

thresholdFaceMaskDetection: 75

registration:
    numFontPics: 2
    numLeftPics: 2
    numRightPics: 2
    stackNumberPics: 6
    leftThreshold: -18
    rightThreshold: 15
    frontRange: 44
    frameBetweenCapture: 3

measureTemperature:
    offsetTemperature: 3
    numberMaxThermalPoints: 16
    offsetDistCoeffecient: -0.0000212
    offsetDistIntercept: 1.654018585

display:
    enableThermalFrame: False

personTracking:
    NoOfDisapearFrames: 30
    bufSizeTempPersonTracking: 6
    bufSizeNameAndIdPersonTracking: 3
    thresholdTempOfFever: 38
