activatedDevice: true
brightIncrementForFaceDetection: 60
buildingId: 1
calibrationTimeForUser: 5
faceDetectionThreshold: 0.69
feverTemperature: 41.0
limitNotifications: 7
limitRecords: 5
offsetTemperature: -2.473107418801611
