activatedDevice: true
brightIncrementForFaceDetection: 33
buildingId: 1
calibrationTimeForUser: 5
faceDetectionThreshold: 0.62
feverTemperature: 37.5
limitNotifications: 7
limitRecords: 5
offsetTemperature: -1.6842666235365584
