activatedDevice: true
brightIncrementForFaceDetection: 0
buildingId: 116
calibrationTimeForUser: 5
enableOnePersonMeasurement: false
faceDetectionThreshold: 0.8
feverTemperature: 37.99
limitNotifications: 7
limitRecords: 5
offsetTemperature: -3.099283307219359
