activatedDevice: true
brightIncrementForFaceDetection: 33
buildingId: 1
calibrationTimeForUser: 5
enableOnePersonMeasurement: false
faceDetectionThreshold: 0.79
feverTemperature: 37.99
limitNotifications: 7
limitRecords: 5
offsetTemperature: -2.242613055342396
