activatedDevice: true
brightIncrementForFaceDetection: 33
buildingId: 1
calibrationTimeForUser: 5
enableOnePersonMeasurement: true
faceDetectionThreshold: 0.9
feverTemperature: 37.99
limitNotifications: 7
limitRecords: 5
offsetTemperature: -2.242613055342396
