buildingId: 1
calibrationTimeForUser: 4
feverTemperature: 41.0
limitNotifications: 7
limitRecords: 5
offsetTemperature: -2.3189353350000275
registration:
  frontRange: 44
  leftThreshold: -18
  rightThreshold: 15
